# Android SDK Setup Script for Windows
# Sets up Android SDK with essential components for building APKs

param(
    [string]$SdkPath = "$env:LOCALAPPDATA\Android\Sdk"
)

Write-Host "Android SDK Setup Script" -ForegroundColor Green
Write-Host "=========================" -ForegroundColor Green

# Create SDK directory structure
Write-Host "Creating SDK directory structure..."
New-Item -ItemType Directory -Path $SdkPath -Force | Out-Null
New-Item -ItemType Directory -Path "$SdkPath\cmdline-tools" -Force | Out-Null
New-Item -ItemType Directory -Path "$SdkPath\platform-tools" -Force | Out-Null
New-Item -ItemType Directory -Path "$SdkPath\platforms" -Force | Out-Null
New-Item -ItemType Directory -Path "$SdkPath\build-tools" -Force | Out-Null

# Set environment variables
Write-Host "Setting environment variables..."
[System.Environment]::SetEnvironmentVariable("ANDROID_HOME", $SdkPath, [System.EnvironmentVariableTarget]::User)
[System.Environment]::SetEnvironmentVariable("ANDROID_SDK_ROOT", $SdkPath, [System.EnvironmentVariableTarget]::User)

# Update PATH
$currentPath = [System.Environment]::GetEnvironmentVariable("PATH", [System.EnvironmentVariableTarget]::User)
$androidPaths = @(
    "$SdkPath\platform-tools",
    "$SdkPath\cmdline-tools\latest\bin",
    "$SdkPath\tools"
)

foreach ($androidPath in $androidPaths) {
    if ($currentPath -notlike "*$androidPath*") {
        $currentPath += ";$androidPath"
    }
}
[System.Environment]::SetEnvironmentVariable("PATH", $currentPath, [System.EnvironmentVariableTarget]::User)

# Set for current session
$env:ANDROID_HOME = $SdkPath
$env:ANDROID_SDK_ROOT = $SdkPath
$env:PATH = "$env:PATH;$SdkPath\platform-tools;$SdkPath\cmdline-tools\latest\bin"

Write-Host "Environment variables configured:"
Write-Host "   ANDROID_HOME: $SdkPath"
Write-Host "   ANDROID_SDK_ROOT: $SdkPath"

# Download Command Line Tools
Write-Host "Downloading Android SDK Command Line Tools..."
$cmdlineToolsUrl = "https://dl.google.com/android/repository/commandlinetools-win-11076708_latest.zip"
$cmdlineToolsZip = "$env:TEMP\commandlinetools-win.zip"
$cmdlineToolsDir = "$SdkPath\cmdline-tools"

try {
    Invoke-WebRequest -Uri $cmdlineToolsUrl -OutFile $cmdlineToolsZip -UseBasicParsing
    Write-Host "Downloaded command line tools"
    
    # Extract the zip file
    Write-Host "Extracting command line tools..."
    Add-Type -AssemblyName System.IO.Compression.FileSystem
    [System.IO.Compression.ZipFile]::ExtractToDirectory($cmdlineToolsZip, "$cmdlineToolsDir\temp")
    
    # Move contents to proper location
    if (Test-Path "$cmdlineToolsDir\temp\cmdline-tools") {
        Move-Item "$cmdlineToolsDir\temp\cmdline-tools" "$cmdlineToolsDir\latest" -Force
        Remove-Item "$cmdlineToolsDir\temp" -Recurse -Force
        Write-Host "Command line tools extracted successfully"
    }
    
    # Clean up
    Remove-Item $cmdlineToolsZip -Force
    
} catch {
    Write-Warning "Failed to download command line tools: $($_.Exception.Message)"
    Write-Host "You may need to download manually from: https://developer.android.com/studio#command-tools"
}

# Download Platform Tools (ADB, Fastboot)
Write-Host "Downloading Platform Tools..."
$platformToolsUrl = "https://dl.google.com/android/repository/platform-tools_r35.0.1-windows.zip"
$platformToolsZip = "$env:TEMP\platform-tools-win.zip"

try {
    Invoke-WebRequest -Uri $platformToolsUrl -OutFile $platformToolsZip -UseBasicParsing
    Write-Host "Downloaded platform tools"
    
    # Extract platform tools
    Write-Host "Extracting platform tools..."
    [System.IO.Compression.ZipFile]::ExtractToDirectory($platformToolsZip, $SdkPath)
    Write-Host "Platform tools extracted successfully"
    
    # Clean up
    Remove-Item $platformToolsZip -Force
    
} catch {
    Write-Warning "Failed to download platform tools: $($_.Exception.Message)"
}

# Create a basic local.properties file for the project
$localPropsFile = "C:\Users\david\OneDrive\Documents\projects\AI Projects\bahai-resource-library\android-app\local.properties"
Write-Host "Creating local.properties file..."
$localPropsContent = @"
# This file was automatically generated by setup_android_sdk.ps1
# Location of the SDK. This is only used by Gradle.
sdk.dir=$($SdkPath.Replace('\', '\\'))
"@

# Create android-app directory if it doesn't exist
$androidAppDir = Split-Path $localPropsFile -Parent
if (!(Test-Path $androidAppDir)) {
    New-Item -ItemType Directory -Path $androidAppDir -Force | Out-Null
}

Set-Content -Path $localPropsFile -Value $localPropsContent -Force
Write-Host "Created local.properties at: $localPropsFile"

# Install essential SDK components using sdkmanager
if (Test-Path "$SdkPath\cmdline-tools\latest\bin\sdkmanager.bat") {
    Write-Host "Installing essential SDK components..."
    
    $sdkComponents = @(
        "platforms;android-34",
        "platforms;android-33", 
        "build-tools;34.0.0",
        "build-tools;33.0.2"
    )
    
    foreach ($component in $sdkComponents) {
        Write-Host "   Installing $component..."
        try {
            $process = Start-Process -FilePath "$SdkPath\cmdline-tools\latest\bin\sdkmanager.bat" -ArgumentList "--sdk_root=$SdkPath", $component, "--accept-licenses" -Wait -PassThru -WindowStyle Hidden
            if ($process.ExitCode -eq 0) {
                Write-Host "   Successfully installed $component"
            } else {
                Write-Warning "   Failed to install $component"
            }
        } catch {
            Write-Warning "   Failed to install $component`: $($_.Exception.Message)"
        }
    }
} else {
    Write-Warning "SDK Manager not found. You may need to install SDK components manually through Android Studio."
}

Write-Host ""
Write-Host "Android SDK Setup Complete!" -ForegroundColor Green
Write-Host "===========================" -ForegroundColor Green
Write-Host "SDK Location: $SdkPath"
Write-Host ""
Write-Host "Next Steps:"
Write-Host "1. Restart Android Studio"
Write-Host "2. Android Studio should now detect the SDK automatically"
Write-Host "3. If prompted, point Android Studio to: $SdkPath"
Write-Host "4. Your project's local.properties file has been updated"
Write-Host ""
Write-Host "You can now:"
Write-Host "   - Build your Bahai Resource Library APK"
Write-Host "   - Use './gradlew assembleRelease' command"
Write-Host "   - Deploy to Android devices and emulators"
Write-Host ""
Write-Host "Environment changes take effect after restarting your terminal/IDE"